#使用spring cloud config 从git上获取配置文件
server:
  port: 18888
spring:
  application:
    name: config-server
    index: ${random.long}
  cloud:
    config:
      server:
        git:
          username: ${GIT_USERNAME:lin79xo@163.com}
          password: ${GIT_PASSWORD:7160893xo}
          uri: ${GIT_URL:https://github.com/linqijin/cloud-demo-config.git}
          search-paths: dev*
#    stream:
#      kafka:
#        binder:
#          zk-nodes: ${ZK_NODES:localhost:2181}
#          brokers: ${KAFKA_BROKERS:localhost:9092}
management:
  security:
    enabled: false

#注册到注册中心
eureka:
  client:
    service-url:
      # 指定eureka server通信地址，注意/eureka/小尾巴不能少
      defaultZone: http://localhost:8761/eureka/
  instance:
    # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server
    prefer-ip-address: true